export default{
    UP_CLASSIFY_HOME:'UP_CLASSIFY_HOME',//上部信息
    UP_VIP_SCHEDULAR:'UP_VIP_SCHEDULAR',//获取优先购票
    UP_HOT_SRECOMMEND:"UP_HOT_SRECOMMEND",//获取热门演出
    UP_TOUR_RECOMMEND:"UP_TOUR_RECOMMEND",//获取巡回演出
}